openapi: 3.0.2
info:
  title: API chess.com
  version: 1.0.0
  description: |-
    This is API for chess.com

servers:
  - url: https://api.chess.com/pub
tags:
  - name: player
    description: Player
paths:
  /player/{playerName}/games/{year}/{month}:
    get:
      tags:
        - player
      parameters:
        - name: playerName
          in: path
          description: Player name
          required: true
          schema:
            type: string
        - name: year
          in: path
          description: Year
          required: true
          schema:
            type: integer
            format: int32
            pattern: \d{4}
        - name: month
          in: path
          description: Month (1-12)
          required: true
          schema:
            type: integer
            format: int32
            pattern: (0[1-9]|1[012])
      summary: Player Game Monthly Archive
      description: Player Game Monthly Archive
      operationId: playerGameMonthlyArchive
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameList'

components:
  schemas:
    GameList:
      type: object
      properties:
        games:
          type: array
          items:
            $ref: '#/components/schemas/Game'


    Game:
      type: object
      properties:
        url:
          type: string
          format: uri
        pgn:
          type: string
        time_control:
          type: string
        end_time:
          type: integer
          format: int32
        rated:
          type: boolean
        tcn:
          type: string
        uuid:
          type: string
          format: uuid
        initial_setup:
          type: string
        fen:
          type: string
        time_class:
          type: string
        rules:
          type: string
        white:
          $ref: '#/components/schemas/GamePlayer'
        black:
          $ref: '#/components/schemas/GamePlayer'

    GamePlayer:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        rating:
          type: integer
          format: int32
        "@id":
          type: string
          format: uri
        result:
          type: string
        username:
          type: string


