image: node:latest

cache:
  paths:
    - node_modules

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - yarn
    - yarn build
    - yarn firebase use --token $FIREBASE_DEPLOY_KEY
    - yarn firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
