version: "3.9"

networks:
  chess_network:
    external: false

services:
  chess-db-pg:
    container_name: chess-db-pg
    image: 'postgres:latest'
    ports:
      - 5432:5432
    networks:
      - chess_network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: chessanalizer

  chess-db-neo4j:
    container_name: chess-db-neo4j
    image: 'neo4j:latest'
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - chess_network
    environment:
      NEO4J_AUTH: neo4j/qwerty123
    volumes:
      - ./_docker/neo4j/data:/data
      - ./_docker/neo4j/logs:/logs
      - ./_docker/neo4j/import:/var/lib/neo4j/import
      - ./_docker/neo4j/plugins:/plugins

  chess-rabbitmq:
    container_name: 'chess-rabbitmq'
    build: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: qwerty123
    volumes:
        - ./_docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./_docker/rabbitmq/log/:/var/log/rabbitmq/
    networks:
        - chess_network

  chess-board:
    container_name: chess-board
    build: board
    ports: 
      - "3000:3000"
    networks:
      - chess_network

