openapi: 3.0.2
info:
  title: CHESS ANALYZER
  version: 1.0.0
  description: |-
    This is API for Chess Analyzer

tags:
  - name: game
    description: game
paths:
  /api/v1/game/update:
    post:
      tags:
        - game
      summary: Update game data
      description: Update game data
      operationId: updateGameData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGameAction'
      responses:
        '200':
          description: Successful operation


components:
  schemas:
    UpdateGameAction:
      type: object
      properties:
        month:
          type: string
          pattern: (0[1-9]|1[012])
        year:
          type: string
          pattern: \d{4}
