openapi: 3.0.2
info:
  title: CHESS ANALYZER
  version: 1.0.0
  description: |-
    This is API for Chess Analyzer

tags:
  - name: authorization
    description: authorization
  - name: game
    description: game
paths:
  /api/v1/authorization/signin:
    post:
      tags:
        - authorization
      summary: User signin
      description: User signin
      operationId: signin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninAction'
      responses:
        '200':
          description: Token created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEntry'

  /api/v1/game/update:
    post:
      tags:
        - game
      summary: Update game data
      description: Update game data
      operationId: updateGameData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGameAction'
      responses:
        '200':
          description: Successful operation


components:
  schemas:
    SigninAction:
      type: object
      properties:
        login:
          type: string
        password:
          type: string

    UpdateGameAction:
      type: object
      properties:
        month:
          type: string
          pattern: (0[1-9]|1[012])
        year:
          type: string
          pattern: \d{4}

    UserEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        chessId:
          type: string
          format: uuid
